---
strictness: high
test-warnings: true
doc-warnings: true
member-warnings: false

ignore-paths:
  - benchmark
  - playground
  - tests
  - analysis

ignore-patterns:
  - setup.py

pep8:
  options:
    max-line-length: 120

pylint:
  run: true
  enable:
    - duplicate-code
  disable:
    - cyclic-import
    - consider-using-enumerate
    - import-error
    - invalid-name
    - logging-format-interpolation
    - logging-fstring-interpolation
    - missing-docstring
    - not-context-manager
    - no-else-return
    - protected-access
    - too-few-public-methods
    - too-many-arguments
    - too-many-locals
    - too-many-branches
    - too-many-statements
    - too-many-lines
    - too-many-instance-attributes
    - too-many-function-args
    - unused-argument
    - useless-suppression
    - wrong-import-error
  options:
    max-line-length: 120
    ignored-argument-names: arg|args|kwargs
    max-attributes: 10
    max-nested-blocks: 6
    docstring-min-length: 5

dodgy:
  run: true

pep257:
  disable:
    # - D102  # Missing doctring in public method
    # - D103  # Missing doctring in public method
    - D104  # Missing doctring in public package
    - D105  # Missing doctring in magic method
    - D107  # Missing docstring in __init__
    - D203  # Blank line before class docstring
    - D212  # Multi-line docstring should start at first line
    - D213  # Multi-line docstring summary should start at the second line
    - D406  # Section name should end with newline
    - D407  # Missing dashed underline after section
    - D413  # Missing blank line after last section

mccabe:
  run: true
  disable:
    - MC0001 # A function is too complicated

mypy:
  run: false
  options:
    ignore-missing-imports: true

pyflakes:
  run: false
