python test_install.py 
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py 
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py 
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py 
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py
sleep 2
python test_install.py