export PYTHONPATH=$HOME/alpa-proj/EasyLM:$PYTHONPATH
python3 run_easylm_flax.py \
    --output_dir="./output" \
    --model_name_or_path="$HOME/alpa-proj/llama-7b" \
    --dataset_name="wikitext" \
    --dataset_config_name="wikitext-2-raw-v1" \
    --do_train --do_eval \
    --block_size="1024" \
    --per_device_train_batch_size="32" \
    --per_device_eval_batch_size="32" \
    --num_micro_batches 64 \
    --operator_parallel 2 \
    --pipeline_parallel 2 \
    --dtype="float16" \
    --learning_rate="5e-4" --warmup_steps="2000" \
    --adam_beta1="0.9" --adam_beta2="0.98" --weight_decay="0.0" \
    --overwrite_output_dir \
    --num_train_epochs="10" \
    --logging_steps="5" \
    --save_steps="40" \
    --eval_steps="25"
