name: Build Jaxlib and Jax

#on: workflow_dispatch

on:
  pull_request:
    branches: [main]

jobs:
  build-image:
    name: Build JaxLib image
    runs-on: [self-hosted]
    steps:
      # checkout repo
      - uses: actions/checkout@v2
      - name: build image
        run: |
          cd build
          pwd
          ls
          docker build . -t build-jaxlib-image

      -name: Compile Jaxlib
        run: |
          pwd
          ls
          mkdir -p dist
          docker run --gpus all --tmpfs /build:exec --rm -v $(pwd)/dist:/dist build-jaxlib-image 3.8.0 cuda
