name: Release Alpa and Jaxlib

on:
  release:
    types: [created]


env:
  TWINE_USERNAME: "__token__"
  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}


jobs:

  release-jaxlib:
    runs-on: [ self-hosted ]

    steps:

      - uses: actions/checkout@v3

      - name: clean up images
        run: |
          docker image prune -f

      - name: build image
        run: |
          docker build -t build-jaxlib-image -f docker/build_jaxlib.Dockerfile docker/

      - name: Compile Jaxlib
        run: |
          mkdir -p dist
          docker run --gpus all --tmpfs /build:exec \
          --rm -v $(pwd)/dist:/dist build-jaxlib-image \
          3.8 cuda 11.1 main

      # change this to publishing to pypi
      - name: Publish to local
        run: |
          echo "Move the Jaxlib binary"
          mv dist/*.whl /data/alpa-dist/jaxlib-alpa/*.whl



  release-alpa:

    runs-on: [self-hosted]

    needs: release-jaxlib

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine six auditwheel pybind11 cmake

      - name: Build and publish
        run: |
          export VERSION=$(./GENVER --pep440)
          python setup.py sdist bdist_wheel
          ls -ltr dist/
          twine upload --repository testpypi dist/*

      - name: Bump VERSION and commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b actions/version-bump
          cat VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}' > VERSION.tmp && mv VERSION.tmp VERSION
          git add VERSION
          git commit -m "Bump candidate version"

      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: actions/version-bump
          force: true

      - name: Create version-bump PR
        uses: repo-sync
